### ISSUE TITLE
Compilation error

### ISSUE THREAD

**Issue by linsson** [lemire/vectorclass#1]
Hi,

First of all I apologize in case my post is not suitable for being here.

I am trying to build IQ-TREE which makes use of vectorclass which seems to return an error:

-- The C compiler identification is GNU 4.8.3
-- The CXX compiler identification is GNU 4.8.3
-- Check for working C compiler: /usr/local/gcc/4.8.3/gcc/bin/gcc
-- Check for working C compiler: /usr/local/gcc/4.8.3/gcc/bin/gcc -- works
-- Detecting C compiler ABI info
-- Detecting C compiler ABI info - done
-- Check for working CXX compiler: /usr/local/gcc/4.8.3/gcc/bin/g++
-- Check for working CXX compiler: /usr/local/gcc/4.8.3/gcc/bin/g++ -- works
-- Detecting CXX compiler ABI info
-- Detecting CXX compiler ABI info - done
IQ-TREE flags : 
Builde mode   : Release
Target OS     : Unix
Compiler      : GNU Compiler (gcc)
Target binary : 64-bit
OpenMP        : Yes
MPI           : NONE
Vectorization : SSE3/AVX/AVX2
C flags       :  -fPIC -O2 -pipe -march=native -mtune=native    -I/usr/local/gcc/4.8.3//eigen/3.3.4/include    -pthread  -O3 -g -ffunction-sections -fdata-sections
CXX flags     :  -fPIC -O2 -pipe -march=native -mtune=native    -I/usr/local/gcc/4.8.3//eigen/3.3.4/include    -std=c++11 -fopenmp -pthread  -O3 -g -ffunction-sections -fdata-sections
LINKER flags  :     -rdynamic  -Wl,--gc-sections
-- Looking for gettimeofday
-- Looking for gettimeofday - found
-- Looking for getrusage
-- Looking for getrusage - found
-- Looking for GlobalMemoryStatusEx
-- Looking for GlobalMemoryStatusEx - not found
-- Looking for strndup
-- Looking for strndup - found
CMake Warning at CMakeLists.txt:438 (find_package):
  By not providing "FindBacktrace.cmake" in CMAKE_MODULE_PATH this project
  has asked CMake to find a package configuration file provided by
  "Backtrace", but CMake did not find one.

  Could not find a package configuration file provided by "Backtrace" with
  any of the following names:

    BacktraceConfig.cmake
    backtrace-config.cmake

  Add the installation prefix of "Backtrace" to CMAKE_PREFIX_PATH or set
  "Backtrace_DIR" to a directory containing one of the above files.  If
  "Backtrace" provides a separate development package or SDK, be sure it has
  been installed.

-- Found ZLIB: /usr/lib/x86_64-linux-gnu/libz.so (found version "1.2.8") 
Using system zlib
-- Configuring done
-- Generating done
-- Build files have been written to: /usr/local/src/software_scientifico/IQ-TREE-1.6.2/build
Scanning dependencies of target kernelfma
[  0%] Building CXX object CMakeFiles/kernelfma.dir/tree/phylokernelfma.cpp.o
In file included from /usr/local/src/software_scientifico/IQ-TREE-1.6.2/vectorclass/vectorclass.h:41:0,
                 from /usr/local/src/software_scientifico/IQ-TREE-1.6.2/vectorclass/vectormath_common.h:35,
                 from /usr/local/src/software_scientifico/IQ-TREE-1.6.2/vectorclass/vectormath_exp.h:38,
                 from /usr/local/src/software_scientifico/IQ-TREE-1.6.2/tree/phylokernelfma.cpp:9:
/usr/local/src/software_scientifico/IQ-TREE-1.6.2/vectorclass/vectori128.h: In function ‘Vec8sb operator>(const Vec8us&, const Vec8us&)’:
/usr/local/src/software_scientifico/IQ-TREE-1.6.2/vectorclass/vectori128.h:1794:38: error: could not convert ‘Vec8s((* & _mm_comgt_epu16((& a)->Vec8us::<anonymous>.Vec8s::operator __m128i(), (& b)->Vec8us::<anonymous>.Vec8s::operator __m128i())))’ from ‘Vec8s’ to ‘Vec8sb’
     return (Vec8s)_mm_comgt_epu16(a,b);
                                      ^
make[2]: *** [CMakeFiles/kernelfma.dir/tree/phylokernelfma.cpp.o] Error 1
make[1]: *** [CMakeFiles/kernelfma.dir/all] Error 2
make: *** [all] Error 2

Please, could you give me any clue to solve this problem?

Thanks!

**Comment by lemire** [comment]
You probably should inquire with the maintainers of the IQ-TREE project? I don't know the first thing about IQ-TREE. Sorry.

**Comment by linsson** [comment]
I see, could you please tell me only if there is any known issue with gcc v. 4.8.3?

**Comment by lemire** [comment]
I am not sure I understand your question.

**Comment by linsson** [comment]
Just asking if vectorclass uses some instruction set which is not supported by gcc 4.8.3 or something of the kind (Hope it is clearer now).

**Comment by lemire** [comment]
@linsson  How many different compilers have you tried?

If you think that there is an issue with your specific compiler, the correct approach is to try with another one. (They are free.)


Ok. But let us see. It says that there is an error at line 1794 of file vectori128.h. Interestingly, there is no code at that line...

https://github.com/lemire/vectorclass/blob/master/vectori128.h#L1794


So you probably did not get the vectorclass from this GitHub repo. Hence, I suggest you inquire with whoever provided you with the vectorclass library.
